name: project_environment
channels:
  - conda-forge
dependencies:
  - setuptools=50.3.0
  - wheel=0.35.1
  - python=3.7
  - pip
  - pip:
    - numpy==1.18.5
    - pandas==0.23.4
    - imgaug==0.4.0
    - azureml-defaults
    - glob2==0.7
    - opencv-python==4.1.2.30
    - tensorflow==2.3.1
    - tensorflow-addons==0.11.2
    - pyyaml
    - bunch==1.0.1
    - scikit-learn==0.22.2.post1
    - wandb
    - matplotlib
