name: project_environment
channels:
  - conda-forge
dependencies:
  - setuptools=50.3.0
  - wheel=0.35.1
  - python=3.7
  - pip==20.2
  - pip:
    - numpy==1.19.5
    - pandas==0.25.3
    - matplotlib==3.3.4
    - scikit-learn==0.22.2.post1
    - glob2==0.7
    - bunch==1.0.1
    - pyyaml
    - tensorflow==2.4.3
    - tensorflow-addons==0.13.0
    - imgaug==0.4.0
    - opencv-python==4.1.2.30
    - wandb
    - azureml-defaults
    - azureml-dataprep[fuse,pandas]
    - cgmzscore==2.0.3
