name: CGM_QA_Pipeline
channels:
  - conda-forge
dependencies:
  - setuptools=50.3.0
  - wheel=0.35.1
  - python=3.7
  - pip
  - nb_conda_kernels==2.2.1
  - scikit-image
  - pip:
    - azure-cli==2.0.69
    - azureml-sdk[notebooks,automl]==1.18.0
    - papermill==1.0.1
    - nbconvert==5.6.0
    - matplotlib==3.2.1
    - glob2==0.7
    - tensorflow==2.3.1
    - tensorflow-addons==0.11.2
    - bunch==1.0.1
