name: CGM_QA_Pipeline
channels:
  - conda-forge
dependencies:
  - cmake
  - setuptools=50.3.0
  - wheel=0.36.2
  - python=3.7
  - pip==20.2
  - nb_conda_kernels==2.2.1
  - scikit-image
  - pip:
    - numpy==1.19.5
    - pandas==0.25.3
    - matplotlib==3.3.4
    - scikit-learn==0.22.2.post1
    - glob2==0.7
    - bunch==1.0.1
    - pyyaml
    - tensorflow==2.4.3
    - tensorflow-addons==0.13.0
    - cgmzscore==2.0.3
    - azure-cli==2.25.0
    - azureml-sdk==1.31.0
